### ISSUE TITLE
Configuration File and Parser for Model and Vector Store Selection

### ISSUE THREAD

**Issue by jeipollack** [jeipollack/euclid_rag#11]
Add a configuration file and a parser to allow developers to specify which LLM model, embedding model, and vector store to use when deploying the app.

h3. Background & Motivation

Currently, our app does not have a structured way to swap between different models or vector stores. Introducing a static configuration file will:

- Allow developers to easily configure the app without modifying the code.
- Enable flexibility in choosing models and storage backends depending on the deployment environment.
- Improve maintainability by centralizing configuration options.

h3. Requirements

**1. Static configuration file (e.g., config.yaml or config.json)**

- Defines the LLM model, embedding model, and vector store options.
- Should be human-readable and easy to edit.
- No runtime modifications—changes require restarting the app.

**2. Parser to load the configuration**

- Reads from the static config file at startup.
- Validates and applies the configuration.
- Logs warnings for missing or incorrect values.

**Example: `config.yaml`**

```
llm:
  model: "gpt-4"
  provider: "openai"
  api_key: "${OPENAI_API_KEY}"  # Read from env variable


embeddings:
  model: "text-embedding-ada-002"
  provider: "openai"

vector_store:
  type: "faiss"
  index_path: "data/index.faiss"

```
(Note: API keys should not be hardcoded—we can support environment variables for security.)

h3. Tasks

- [ ]  Define the schema for the config file.
- [ ]  Implement a parser to read and validate the config.
- [ ]  Integrate the parser into the app’s initialization.
- [ ]  Add logging for missing or incorrect values.
- [ ]  Write documentation on how to use the config file.

h3. Open Questions

- Should we allow fallbacks/defaults if no config is provided?
- Should we support multiple vector store types (e.g., faiss, chroma, pinecone)?
- Do we need a test suite for different config scenarios?
